### PR TITLE
Initial 1.8 port

### PR DESCRIPTION
**Pull request by iLexiconn**
Enchanting stuff doesn't work yet, because enchantmentsList is private. I also couldn't get the access transformer to work.

Don't merge this into master, but into a new branch. (I couldn't create a new branch.)

### CODE REVIEW

**Comment by darkhax** [comment]
I will have to wait and see what @lclc98 thinks about this. Both of us have already decided that we have very little interest in moving over to 1.8 right now, with a few minor exceptions here and there. That being said, a few people such as Subaraki have asked for a 1.8 update of the mod so that they can make 1.8 builds of their mods. I am going to leave it up to @lclc98 :p

**Comment by lclc98** [comment]
Sorry for not responding that fast. At the moment I will be staying on 1.7.10 until both Darkhax and I are happy to move on. This will likely be after we release a few of our mods that have been planned to be released soon. Keep the PR I will get to reading it fully when i get time and will try to merge soon.

**Comment by darkhax** [comment]
To elaborate more on lclc98's reply, neither of us is ready to make 1.8 the targeted version for this project right now. The 1.8 update is going to take a LOT of work for this mod, and will require doing things such as rewriting all of our ASM, and a few other parts of the code. We have several projects which build off of Bookshelf which I would eventually like to get ported over to 1.8 though. I will open a new 1.8 branch for now.

**Comment by iLexiconn** [comment]
The ASM should work fine already,  I checked all the field and method names so that shouldn't be a problem. And I think you should wait for a 1.8 Forge 1.8.8 anyways.

**Comment by lclc98** [comment]
i have started a 1.8.8 update in my ide, but it still needs a lot of work, i didn't spend much time. If u want to update to 1.8.8 and do a pr to the 1.8.8 branch I will merge it in else I will try to finish when i get more time

**Comment by iLexiconn** [comment]
Yeah, that's why I closed the pr. I'll kate a look at it later, I'm pretty busy atm. This pr mostly works in 1.8.8 already, except some mappings and the tessellator.

**Comment by darkhax** [comment]
I am setting up a 1.8.8 workspace now. Going to try some things out.

**Pull request closed without merging**
