### PR TITLE
Added AbstractTileEntity and SkullUtils

### PR DESCRIPTION
**Pull request by iLexiconn**

### CODE REVIEW

**Comment by darkhax** [comment]
The skull utils look good, however I don't really understand what the AbstractTileEntity is all about. I get that you are using some new methods to handle syncing of the TIleEntity NBT, but this is naturally handled by those four methods you override? Am I missing the point? lol

**Comment by iLexiconn** [comment]
It's just a small helper class to make the tileentity class look nicer. (Just like the AbstractMessage does)

**Comment by darkhax** [comment]
But with AbstractMessage, you are uniting the IMessage and IMessageHandler into a single class. Can you link me to something that makes use of this, so I can see it in action?

**Comment by iLexiconn** [comment]
I used this class (
https://github.com/iLexiconn/LLibrary/blob/456f77ff91b112db21817b54317d1d07295e09d0/src/main/java/net/ilexiconn/llibrary/common/tileentity/AbstractTileEntity.java)
a lot, but in later versions the sides got split up. It's basically just
for lazy people.

2015-10-30 23:13 GMT+01:00 Tyler Hancock <notifications@github.com>:

**Comment by darkhax** [comment]
Lol, makes sense. I will probably try and write some code to hook into CreativeTabs as well, so we can have all of those skulls present in the creative tab. Could be cool to have a general purpose CreativeTabEvent :)

**Pull request merged**
