### PR TITLE
Added curseforge upload task and LLibrary update checker support

### PR DESCRIPTION
**Pull request by iLexiconn**
To get the curseforge task to work, make a new file called secret.properties.
In that fire you put two properties, the 'curseForgeApiKey' and the 'projectId'.

Create a new api key on the curseforge website, and use it for the curseForgeApiKey property.
Set the projectId to.. well... the project id.

Make sure not to commit this file, everyone can upload files to your curseforge page with that key!

It generates the changelog from the 'versions.json' file. LLibrary also uses this file to check for updates.

I also changed the minecraft folder to 'run', just because Forge changed that a while ago too.

PS: I didn't test any of it, but it *should* work!

### CODE REVIEW

**Comment by darkhax** [comment]
Thank you for writing this. Everything looks good to go, however I think there may be a few conflicts with this, based on how our build server is currently set up. @lclc98 is in charge of the build server, so I will let him review the changes first.

**Comment by iLexiconn** [comment]
If you're talking about the secret file, you can also use system properties. I can change it if you want.

**Comment by darkhax** [comment]
No, it's not that. It's actually an issue with the CurseForge uploading, and changelog. Right now our build server creates a new build every time code is pushed, or merged, so under the current system, this would flood our page with many releases. Our current plan is to set something up that can detect shifts in the major build number, for example 1.1.24 to 1.2.0 and treat those as full on releases. The changelog is also automatically generated using the commit messages.

**Comment by iLexiconn** [comment]
What if you make a system that detects 'Release' in the commit message? If it's detected, generate the changelog, and put it on curseforge.

**Comment by darkhax** [comment]
Yes, that is probably what we will end up doing. Instead of the word 'Release', as it could possibly be used in non release messages, we might use a # in front of it instead, similarly to how GitHub uses # to reference pull requests and issues. Or maybe a different special character.

**Comment by lclc98** [comment]
So i am currently working on a gradle rewrite for most projects of epoxide so they have a good version updating system. After that i will look into this push,

**Comment by darkhax** [comment]
Just to give you an update on the PR, we have finally worked out all of the details for the version system, we have chosen to opt for the exact same system forge uses for the forge project. Which is probably for the best. Right now our current issue is that our build server does not run Java 1.6, and the CurseGradle plugin requires 1.7. Once the update is applied on our server, we should be able to accept.

**Comment by lclc98** [comment]
Thank you for working on this, I needed to work on versioning so I included this in when doing so. Thank you for contributing to bookshelf to improve it.

**Comment by darkhax** [comment]
Hey there, so lclc98 has finished his implementation of CurseGradle, and now there are a few conflicts. Since that was one of the core aspects of this pull, I will close it. I will work on adding the things that are not covered by the CurseGradle system, such as the LLibrary support. Thank you for contributing to the bookshelf project, it is very appreciated!

**Pull request closed without merging**
