### PR TITLE
1.61.1 Upgrade

### PR DESCRIPTION
**Pull request by puggan**
Started with a 1.16.1 upgrade, so put it here as a Draft PR, in-case someone was interested in how its going.

### CODE REVIEW

**Comment by puggan** [comment]
**Help needed:**
Can't find a replacement for `ItemTags.getGeneration()`

https://github.com/Darkhax-Minecraft/Bookshelf/blob/bffcd767dddb9de3f15daaca1415f4d2411b7051/src/main/java/net/darkhax/bookshelf/crafting/item/IngredientPredicate.java#L103

**Comment by puggan** [comment]
*Help Needed*
Can't find a replacement fro `ForgeRegistries.MOD_DIMENSIONS`

https://github.com/Darkhax-Minecraft/Bookshelf/blob/62e3cf7c4ee4d692a556196fc8d0c7eacb37b0eb/src/main/java/net/darkhax/bookshelf/util/MCJsonUtils.java#L191-L194

**Comment by Darkhax** [comment]
> 
> 
> _Help Needed_
> Can't find a replacement fro `ForgeRegistries.MOD_DIMENSIONS`
> 
> https://github.com/Darkhax-Minecraft/Bookshelf/blob/62e3cf7c4ee4d692a556196fc8d0c7eacb37b0eb/src/main/java/net/darkhax/bookshelf/util/MCJsonUtils.java#L191-L194

Dimension related code will need to be nuked. It no longer exists.

**Comment by puggan** [comment]
Now I checked all that I could manage by myself.
here is a list of the stuff that still red in my editor:

java/net/darkhax/bookshelf/crafting/item/IngredientPredicate.java
	refers ItemTags.getGeneration

java/net/darkhax/bookshelf/loot/condition/*.java
	1.15: /net/minecraft/world/storage/loot/conditions/ILootCondition.java
	1.16: /net/minecraft/loot/conditions/ILootCondition.java
	subclass `AbstractSerializer` replaced with `LootConditionType func_230419_b_();`

java/net/darkhax/bookshelf/network/NetworkHelper.java
	refers Dimension

java/net/darkhax/bookshelf/registry/RegistryHelper.java
	refers BiomeProviderType, IBiomeProviderSettings, ChunkGeneratorType, GenerationSettings, AbstractSerializer

java/net/darkhax/bookshelf/util/MCJsonUtils.java
	refers ModDimension
	private LootTableManager.GSON_INSTANCE, is already in accesstransformer.cfg

java/net/darkhax/bookshelf/util/RenderUtils.java
	private BlockModelRenderer.renderQuadsFlat, is already in accesstransformer.cfg

java/net/darkhax/bookshelf/Bookshelf.java
	refering to java/net/darkhax/bookshelf/loot/condition/*.java

**Comment by puggan** [comment]
I got it to build, the last 6 commits are "unsafe", nuked/removed stuff and rewrote loot conditions.

**Comment by puggan** [comment]
Error when entering a world:

`java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Missing required tags: items:forge:axes,items:forge:hoes,items:forge:pickaxes,items:forge:shovels,items:forge:swords,items:forge:tools/axes,items:forge:tools/hoes,items:forge:tools/pickaxes,items:forge:tools/shovels,items:forge:tools/swords
`

**Comment by Darkhax** [comment]
I decided to do the port separately. There was far too much going on in this PR, especially with the change in MCP mappings and many of the changes I wanted to make.

**Pull request closed without merging**
